# Site settings
title: Grounding AI
description: AI Atlas of AI
lang: en

# URL settings
baseurl: "" # Leave blank if deploying to root, e.g., username.github.io
url: "https://grounding-ai.github.io/" # Replace with your GitHub Pages site URL

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "sunrise"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-paginate

# Disable recent posts
entries_layout: grid
show_excerpts: false

include:
  - _pages

# Navigation settings
header_pages:
  - index.md
  - about.md
  - methodology.md
  - who-are-we.md

# Footer (optional)
footer:
  links:
    - title: "About"
      url: /about/
    - title: "Methodology"
      url: /methodology/
    - title: "Who We Are"
      url: /who-are-we/
