# Site settings
title: Grounding AI
description: AI Atlas of AI
lang: en

# URL settings
baseurl: ""
url: "https://grounding-ai.github.io/"

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # Using default skin instead of custom

# Color customization
minimal_mistakes_skin_dark: false
colors:
  background: "#ffffff"
  text: "#687586"
  primary: "#687586"
  links: "#687586"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-paginate

# Site configuration
entries_layout: grid
show_excerpts: false
include:
  - _pages

# Navigation
header_pages:
  - index.md
  - about.md
  - methodology.md
  - who-are-we.md

# Footer
footer:
  links:
    - title: "About"
      url: /about/
    - title: "Methodology"
      url: /methodology/
    - title: "Who We Are"
      url: /who-are-we/
