# Site settings
title: Grounding AI
description: AI Atlas of AI

# Theme settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
include:
  - _pages
  
# Navigation
header_pages:
  - _pages/about.md
  - _pages/methodology.md
  - _pages/who-are-we.md
