# Site settings
title: Grounding AI
description: AI Atlas of AI
lang: en

# URL settings
baseurl: ""
url: "https://grounding-ai.github.io/"

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-paginate

entries_layout: grid
show_excerpts: false
include:
  - _pages

header_pages:
  - index.md
  - about.md
  - methodology.md
  - who-are-we.md

footer:
  links:
    - title: "About"
      url: /about/
    - title: "Methodology"
      url: /methodology/
    - title: "Who We Are"
      url: /who-are-we/
