# Site settings
title: Grounding AI
description: AI Atlas of AI

# Theme settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown

# Navigation
header_pages:
  - about.md
  - methodology.md
  - who-are-we.md
