# Site settings
title: Grounding AI
description: AI Atlas of AI

# Theme settings
remote_theme: pages-themes/minima@v2.5.1
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

# Build settings
markdown: kramdown

# Minima theme settings
minima:
  header_pages:
    - about.md
    - methodology.md
    - who-are-we.md
  
# Social links (optional)
github_username: grounding-ai
